# Generated by Django 4.2.4 on 2023-10-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_album_register_pic_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='pic_id',
        ),
    ]
