# Generated by Django 4.2.4 on 2023-10-15 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0003_remove_register_pic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='pic_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendapp.login'),
            preserve_default=False,
        ),
    ]
